### 
POST {{local}}/getLatestOrders
content-type: application/json

{
"authCode": "...", 
"assetPairs": "...", 
"subscriber": "..."
}

############################################################
# asdasd

### 
POST {{local}}/getLatestTickers
content-type: application/json

{
"authCode": "...", 
"assetPairs": "...", 
"subscriber": "..."
}
### 
POST {{local}}/getLatestBalances
content-type: application/json

{
"authCode": "...", 
"assets": "...", 
"subscriber": "..."
}
### 
POST {{local}}/addRelevantAsset
content-type: application/json

{
"authCode": "...", 
"exchangeName": "...", 
"ourName": "..."
}
### 
POST {{local}}/removeRelevantAsset
content-type: application/json

{
"authCode": "...", 
"ourName": "..."
}
### 
POST {{local}}/addRelevantAssetPair
content-type: application/json

{
"authCode": "...", 
"exchangeName": "...", 
"ourName": "..."
}
### 
POST {{local}}/removeRelevantAssetPair
content-type: application/json

{
"authCode": "...", 
"ourName": "..."
}
### 
POST {{local}}/getRelevantAssets
content-type: application/json

{
"authCode": "..."
}
### 
POST {{local}}/getRelevantAssetPairs
content-type: application/json

{
"authCode": "..."
}
### 
POST {{local}}/getFailingIdentifiers
content-type: application/json

{
"authCode": "..."
}
### 
POST {{local}}/getServiceStatus
content-type: application/json

{
"authCode": "..."
}
### 
POST {{local}}/getNodeId
content-type: application/json

{
"authCode": "..."
}
